export const FETCH_CHAIR_REQUEST="FETCH_CHAIR_REQUEST"
export const FETCH_CHAIR_SUCCESS="FETCH_CHAIR_SUCCESS"
export const FETCH_CHAIR_FAILURE="FETCH_CHAIR_FAILURE"


export const  DELETE_CHAIR_SUCCESS=" DELETE_CHAIR_SUCCESS"
export const  DELETE_CHAIR_FAILURE=" DELETE_CHAIR_FAILURE"